// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

package configpb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	App                  *AppConfig     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Network              *NetworkConfig `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Db                   *DataConfig    `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	Log                  *LogConfig     `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Miner                *MinerConfig   `protobuf:"bytes,5,opt,name=miner,proto3" json:"miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetApp() *AppConfig {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *Config) GetNetwork() *NetworkConfig {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Config) GetDb() *DataConfig {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *Config) GetLog() *LogConfig {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Config) GetMiner() *MinerConfig {
	if m != nil {
		return m.Miner
	}
	return nil
}

type AppConfig struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	CpuProfile           string   `protobuf:"bytes,2,opt,name=cpu_profile,json=cpuProfile,proto3" json:"cpu_profile,omitempty"`
	PubPassword          string   `protobuf:"bytes,3,opt,name=pub_password,json=pubPassword,proto3" json:"pub_password,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfig) Reset()         { *m = AppConfig{} }
func (m *AppConfig) String() string { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()    {}
func (*AppConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *AppConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfig.Unmarshal(m, b)
}
func (m *AppConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfig.Marshal(b, m, deterministic)
}
func (m *AppConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfig.Merge(m, src)
}
func (m *AppConfig) XXX_Size() int {
	return xxx_messageInfo_AppConfig.Size(m)
}
func (m *AppConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfig proto.InternalMessageInfo

func (m *AppConfig) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *AppConfig) GetCpuProfile() string {
	if m != nil {
		return m.CpuProfile
	}
	return ""
}

func (m *AppConfig) GetPubPassword() string {
	if m != nil {
		return m.PubPassword
	}
	return ""
}

func (m *AppConfig) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type NetworkConfig struct {
	P2P                  *P2PConfig `protobuf:"bytes,1,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Rpc                  *RPCConfig `protobuf:"bytes,2,opt,name=rpc,proto3" json:"rpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NetworkConfig) Reset()         { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()    {}
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}
func (m *NetworkConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkConfig.Unmarshal(m, b)
}
func (m *NetworkConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkConfig.Marshal(b, m, deterministic)
}
func (m *NetworkConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkConfig.Merge(m, src)
}
func (m *NetworkConfig) XXX_Size() int {
	return xxx_messageInfo_NetworkConfig.Size(m)
}
func (m *NetworkConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkConfig proto.InternalMessageInfo

func (m *NetworkConfig) GetP2P() *P2PConfig {
	if m != nil {
		return m.P2P
	}
	return nil
}

func (m *NetworkConfig) GetRpc() *RPCConfig {
	if m != nil {
		return m.Rpc
	}
	return nil
}

type DataConfig struct {
	DataDir              string   `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	DbType               string   `protobuf:"bytes,2,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataConfig) Reset()         { *m = DataConfig{} }
func (m *DataConfig) String() string { return proto.CompactTextString(m) }
func (*DataConfig) ProtoMessage()    {}
func (*DataConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}
func (m *DataConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataConfig.Unmarshal(m, b)
}
func (m *DataConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataConfig.Marshal(b, m, deterministic)
}
func (m *DataConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataConfig.Merge(m, src)
}
func (m *DataConfig) XXX_Size() int {
	return xxx_messageInfo_DataConfig.Size(m)
}
func (m *DataConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataConfig proto.InternalMessageInfo

func (m *DataConfig) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

func (m *DataConfig) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

type LogConfig struct {
	LogDir               string   `protobuf:"bytes,1,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	LogLevel             string   `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	DisableCprint        bool     `protobuf:"varint,3,opt,name=disable_cprint,json=disableCprint,proto3" json:"disable_cprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogConfig) Reset()         { *m = LogConfig{} }
func (m *LogConfig) String() string { return proto.CompactTextString(m) }
func (*LogConfig) ProtoMessage()    {}
func (*LogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}
func (m *LogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogConfig.Unmarshal(m, b)
}
func (m *LogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogConfig.Marshal(b, m, deterministic)
}
func (m *LogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogConfig.Merge(m, src)
}
func (m *LogConfig) XXX_Size() int {
	return xxx_messageInfo_LogConfig.Size(m)
}
func (m *LogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogConfig proto.InternalMessageInfo

func (m *LogConfig) GetLogDir() string {
	if m != nil {
		return m.LogDir
	}
	return ""
}

func (m *LogConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *LogConfig) GetDisableCprint() bool {
	if m != nil {
		return m.DisableCprint
	}
	return false
}

type MinerConfig struct {
	PocminerBackend      string   `protobuf:"bytes,1,opt,name=pocminer_backend,json=pocminerBackend,proto3" json:"pocminer_backend,omitempty"`
	SpacekeeperBackend   string   `protobuf:"bytes,2,opt,name=spacekeeper_backend,json=spacekeeperBackend,proto3" json:"spacekeeper_backend,omitempty"`
	MinerDir             string   `protobuf:"bytes,3,opt,name=miner_dir,json=minerDir,proto3" json:"miner_dir,omitempty"`
	MiningAddr           []string `protobuf:"bytes,4,rep,name=mining_addr,json=miningAddr,proto3" json:"mining_addr,omitempty"`
	Generate             bool     `protobuf:"varint,5,opt,name=generate,proto3" json:"generate,omitempty"`
	AllowSolo            bool     `protobuf:"varint,6,opt,name=allow_solo,json=allowSolo,proto3" json:"allow_solo,omitempty"`
	ProofDir             []string `protobuf:"bytes,7,rep,name=proof_dir,json=proofDir,proto3" json:"proof_dir,omitempty"`
	ProofList            string   `protobuf:"bytes,8,opt,name=proof_list,json=proofList,proto3" json:"proof_list,omitempty"`
	Plot                 bool     `protobuf:"varint,9,opt,name=plot,proto3" json:"plot,omitempty"`
	PrivatePassword      string   `protobuf:"bytes,10,opt,name=private_password,json=privatePassword,proto3" json:"private_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerConfig) Reset()         { *m = MinerConfig{} }
func (m *MinerConfig) String() string { return proto.CompactTextString(m) }
func (*MinerConfig) ProtoMessage()    {}
func (*MinerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}
func (m *MinerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerConfig.Unmarshal(m, b)
}
func (m *MinerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerConfig.Marshal(b, m, deterministic)
}
func (m *MinerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerConfig.Merge(m, src)
}
func (m *MinerConfig) XXX_Size() int {
	return xxx_messageInfo_MinerConfig.Size(m)
}
func (m *MinerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MinerConfig proto.InternalMessageInfo

func (m *MinerConfig) GetPocminerBackend() string {
	if m != nil {
		return m.PocminerBackend
	}
	return ""
}

func (m *MinerConfig) GetSpacekeeperBackend() string {
	if m != nil {
		return m.SpacekeeperBackend
	}
	return ""
}

func (m *MinerConfig) GetMinerDir() string {
	if m != nil {
		return m.MinerDir
	}
	return ""
}

func (m *MinerConfig) GetMiningAddr() []string {
	if m != nil {
		return m.MiningAddr
	}
	return nil
}

func (m *MinerConfig) GetGenerate() bool {
	if m != nil {
		return m.Generate
	}
	return false
}

func (m *MinerConfig) GetAllowSolo() bool {
	if m != nil {
		return m.AllowSolo
	}
	return false
}

func (m *MinerConfig) GetProofDir() []string {
	if m != nil {
		return m.ProofDir
	}
	return nil
}

func (m *MinerConfig) GetProofList() string {
	if m != nil {
		return m.ProofList
	}
	return ""
}

func (m *MinerConfig) GetPlot() bool {
	if m != nil {
		return m.Plot
	}
	return false
}

func (m *MinerConfig) GetPrivatePassword() string {
	if m != nil {
		return m.PrivatePassword
	}
	return ""
}

type P2PConfig struct {
	Seeds                string   `protobuf:"bytes,1,opt,name=seeds,proto3" json:"seeds,omitempty"`
	AddPeer              []string `protobuf:"bytes,2,rep,name=add_peer,json=addPeer,proto3" json:"add_peer,omitempty"`
	SkipUpnp             bool     `protobuf:"varint,3,opt,name=skip_upnp,json=skipUpnp,proto3" json:"skip_upnp,omitempty"`
	HandshakeTimeout     uint32   `protobuf:"varint,4,opt,name=handshake_timeout,json=handshakeTimeout,proto3" json:"handshake_timeout,omitempty"`
	DialTimeout          uint32   `protobuf:"varint,5,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	VaultMode            bool     `protobuf:"varint,6,opt,name=vault_mode,json=vaultMode,proto3" json:"vault_mode,omitempty"`
	ListenAddress        string   `protobuf:"bytes,7,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PConfig) Reset()         { *m = P2PConfig{} }
func (m *P2PConfig) String() string { return proto.CompactTextString(m) }
func (*P2PConfig) ProtoMessage()    {}
func (*P2PConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}
func (m *P2PConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PConfig.Unmarshal(m, b)
}
func (m *P2PConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PConfig.Marshal(b, m, deterministic)
}
func (m *P2PConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PConfig.Merge(m, src)
}
func (m *P2PConfig) XXX_Size() int {
	return xxx_messageInfo_P2PConfig.Size(m)
}
func (m *P2PConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PConfig.DiscardUnknown(m)
}

var xxx_messageInfo_P2PConfig proto.InternalMessageInfo

func (m *P2PConfig) GetSeeds() string {
	if m != nil {
		return m.Seeds
	}
	return ""
}

func (m *P2PConfig) GetAddPeer() []string {
	if m != nil {
		return m.AddPeer
	}
	return nil
}

func (m *P2PConfig) GetSkipUpnp() bool {
	if m != nil {
		return m.SkipUpnp
	}
	return false
}

func (m *P2PConfig) GetHandshakeTimeout() uint32 {
	if m != nil {
		return m.HandshakeTimeout
	}
	return 0
}

func (m *P2PConfig) GetDialTimeout() uint32 {
	if m != nil {
		return m.DialTimeout
	}
	return 0
}

func (m *P2PConfig) GetVaultMode() bool {
	if m != nil {
		return m.VaultMode
	}
	return false
}

func (m *P2PConfig) GetListenAddress() string {
	if m != nil {
		return m.ListenAddress
	}
	return ""
}

type RPCConfig struct {
	ApiPortGrpc          string   `protobuf:"bytes,1,opt,name=api_port_grpc,json=apiPortGrpc,proto3" json:"api_port_grpc,omitempty"`
	ApiPortHttp          string   `protobuf:"bytes,2,opt,name=api_port_http,json=apiPortHttp,proto3" json:"api_port_http,omitempty"`
	ApiWhitelist         []string `protobuf:"bytes,3,rep,name=api_whitelist,json=apiWhitelist,proto3" json:"api_whitelist,omitempty"`
	ApiAllowedLan        []string `protobuf:"bytes,4,rep,name=api_allowed_lan,json=apiAllowedLan,proto3" json:"api_allowed_lan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCConfig) Reset()         { *m = RPCConfig{} }
func (m *RPCConfig) String() string { return proto.CompactTextString(m) }
func (*RPCConfig) ProtoMessage()    {}
func (*RPCConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{7}
}
func (m *RPCConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCConfig.Unmarshal(m, b)
}
func (m *RPCConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCConfig.Marshal(b, m, deterministic)
}
func (m *RPCConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCConfig.Merge(m, src)
}
func (m *RPCConfig) XXX_Size() int {
	return xxx_messageInfo_RPCConfig.Size(m)
}
func (m *RPCConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RPCConfig proto.InternalMessageInfo

func (m *RPCConfig) GetApiPortGrpc() string {
	if m != nil {
		return m.ApiPortGrpc
	}
	return ""
}

func (m *RPCConfig) GetApiPortHttp() string {
	if m != nil {
		return m.ApiPortHttp
	}
	return ""
}

func (m *RPCConfig) GetApiWhitelist() []string {
	if m != nil {
		return m.ApiWhitelist
	}
	return nil
}

func (m *RPCConfig) GetApiAllowedLan() []string {
	if m != nil {
		return m.ApiAllowedLan
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "configpb.Config")
	proto.RegisterType((*AppConfig)(nil), "configpb.AppConfig")
	proto.RegisterType((*NetworkConfig)(nil), "configpb.NetworkConfig")
	proto.RegisterType((*DataConfig)(nil), "configpb.DataConfig")
	proto.RegisterType((*LogConfig)(nil), "configpb.LogConfig")
	proto.RegisterType((*MinerConfig)(nil), "configpb.MinerConfig")
	proto.RegisterType((*P2PConfig)(nil), "configpb.P2PConfig")
	proto.RegisterType((*RPCConfig)(nil), "configpb.RPCConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xe1, 0x8e, 0x1b, 0x35,
	0x10, 0xc7, 0x95, 0xdc, 0x25, 0xd9, 0x9d, 0x5c, 0x68, 0x71, 0x8b, 0xba, 0x50, 0x9d, 0x5a, 0x16,
	0x8a, 0x40, 0x95, 0x0e, 0x11, 0x5e, 0x80, 0x70, 0x95, 0xe0, 0x43, 0x8a, 0xa2, 0xa5, 0x88, 0x4f,
	0x68, 0xe5, 0x5d, 0xfb, 0x36, 0x56, 0x9c, 0xf5, 0xc8, 0xeb, 0x5c, 0xd4, 0x07, 0xe0, 0x3d, 0x78,
	0x30, 0x78, 0x06, 0x5e, 0x01, 0x79, 0xbc, 0xde, 0xe4, 0x50, 0xbf, 0x65, 0xfe, 0xf3, 0xb3, 0xc7,
	0xf3, 0x9f, 0xd9, 0xc0, 0x55, 0x6d, 0xda, 0x3b, 0xd5, 0xdc, 0xa0, 0x35, 0xce, 0xb0, 0x24, 0x44,
	0x58, 0xe5, 0x7f, 0x8f, 0x60, 0x7a, 0x4b, 0x01, 0x7b, 0x05, 0x17, 0x1c, 0x31, 0x1b, 0xbd, 0x1c,
	0x7d, 0x3d, 0x5f, 0x3e, 0xb9, 0x89, 0xc8, 0xcd, 0x0a, 0x31, 0x10, 0x85, 0xcf, 0xb3, 0xef, 0x60,
	0xd6, 0x4a, 0x77, 0x34, 0x76, 0x97, 0x8d, 0x09, 0x7d, 0x76, 0x42, 0x7f, 0x09, 0x89, 0x1e, 0x8f,
	0x1c, 0xfb, 0x12, 0xc6, 0xa2, 0xca, 0x2e, 0x88, 0x7e, 0x7a, 0xa2, 0xdf, 0x70, 0xc7, 0x7b, 0x74,
	0x2c, 0x2a, 0x5f, 0x5f, 0x9b, 0x26, 0xbb, 0xfc, 0x7f, 0xfd, 0xb5, 0x69, 0x62, 0x7d, 0x6d, 0x1a,
	0xf6, 0x1a, 0x26, 0x7b, 0xd5, 0x4a, 0x9b, 0x4d, 0x08, 0xfc, 0xe4, 0x04, 0xbe, 0xf5, 0x72, 0x8f,
	0x06, 0x26, 0xff, 0x73, 0x04, 0xe9, 0xf0, 0x7e, 0x96, 0xc1, 0x0c, 0xad, 0xb9, 0x53, 0x5a, 0x52,
	0x97, 0x69, 0x11, 0x43, 0xf6, 0x02, 0xe6, 0x35, 0x1e, 0xca, 0x98, 0x1d, 0x53, 0x16, 0x6a, 0x3c,
	0x6c, 0x7a, 0xe0, 0x73, 0xb8, 0xc2, 0x43, 0x55, 0x22, 0xef, 0xba, 0xa3, 0xb1, 0x82, 0x9a, 0x49,
	0x8b, 0x39, 0x1e, 0xaa, 0x4d, 0x2f, 0xb1, 0xcf, 0x20, 0xd9, 0x9a, 0xce, 0xb5, 0x7c, 0x2f, 0xa9,
	0x89, 0xb4, 0x18, 0xe2, 0xfc, 0x0f, 0x58, 0x3c, 0xf0, 0xc6, 0x37, 0x8b, 0xcb, 0x0f, 0x98, 0xbd,
	0x59, 0x6e, 0x62, 0xb3, 0xb8, 0x44, 0x8f, 0x59, 0xac, 0x7b, 0xa3, 0xcf, 0xb0, 0x62, 0x73, 0x1b,
	0x31, 0x8b, 0x75, 0xfe, 0x03, 0xc0, 0xc9, 0x4c, 0xf6, 0x29, 0x24, 0x82, 0x3b, 0x5e, 0x0a, 0x65,
	0x63, 0x9f, 0x3e, 0x7e, 0xa3, 0x2c, 0x7b, 0x06, 0x33, 0x51, 0x95, 0xee, 0x3d, 0xc6, 0x1e, 0xa7,
	0xa2, 0x7a, 0xf7, 0x1e, 0x65, 0xbe, 0x85, 0x74, 0xf0, 0xd9, 0x53, 0xda, 0x34, 0x67, 0xe7, 0xa7,
	0xda, 0x34, 0xfe, 0xf8, 0x73, 0x48, 0x7d, 0x42, 0xcb, 0x7b, 0xa9, 0xfb, 0x0b, 0x12, 0x6d, 0x9a,
	0xb5, 0x8f, 0xd9, 0x2b, 0xf8, 0x48, 0xa8, 0x8e, 0x57, 0x5a, 0x96, 0x35, 0x5a, 0xd5, 0x3a, 0x32,
	0x29, 0x29, 0x16, 0xbd, 0x7a, 0x4b, 0x62, 0xfe, 0xcf, 0x18, 0xe6, 0x67, 0x93, 0x62, 0xdf, 0xc0,
	0x63, 0x34, 0x35, 0x8d, 0xab, 0xac, 0x78, 0xbd, 0x93, 0xad, 0xe8, 0xab, 0x3e, 0x8a, 0xfa, 0x8f,
	0x41, 0x66, 0xdf, 0xc2, 0x93, 0x0e, 0x79, 0x2d, 0x77, 0x52, 0xe2, 0x19, 0x1d, 0x1e, 0xc2, 0xce,
	0x52, 0xf1, 0xc0, 0x73, 0x48, 0xc3, 0xc5, 0xbe, 0x95, 0x30, 0xb2, 0x84, 0x04, 0xdf, 0xcc, 0x0b,
	0x98, 0xef, 0x55, 0xab, 0xda, 0xa6, 0xe4, 0x42, 0xd8, 0xec, 0xf2, 0xe5, 0x85, 0x9f, 0x79, 0x90,
	0x56, 0x42, 0x58, 0x3f, 0xd0, 0x46, 0xb6, 0xd2, 0x72, 0x27, 0x69, 0xd9, 0x92, 0x62, 0x88, 0xd9,
	0x35, 0x00, 0xd7, 0xda, 0x1c, 0xcb, 0xce, 0x68, 0x93, 0x4d, 0x29, 0x9b, 0x92, 0xf2, 0xab, 0xd1,
	0xc6, 0x17, 0x46, 0x6b, 0xcc, 0x1d, 0x15, 0x9e, 0xd1, 0xcd, 0x09, 0x09, 0xbe, 0xf0, 0x35, 0x40,
	0x48, 0x6a, 0xd5, 0xb9, 0x2c, 0xa1, 0x67, 0x05, 0x7c, 0xad, 0x3a, 0xc7, 0x18, 0x5c, 0xa2, 0x36,
	0x2e, 0x4b, 0xe9, 0x52, 0xfa, 0x4d, 0x26, 0x59, 0x75, 0xcf, 0x9d, 0x3c, 0xad, 0x20, 0xf4, 0x26,
	0x05, 0x3d, 0xae, 0x61, 0xfe, 0xef, 0x08, 0xd2, 0x61, 0x8b, 0xd8, 0x53, 0x98, 0x74, 0x52, 0x8a,
	0xae, 0xb7, 0x34, 0x04, 0x7e, 0x43, 0xb8, 0x10, 0x25, 0x4a, 0x69, 0xb3, 0x31, 0xbd, 0x6e, 0xc6,
	0x85, 0xd8, 0x48, 0x49, 0x23, 0xee, 0x76, 0x0a, 0xcb, 0x03, 0xb6, 0xd8, 0x0f, 0x30, 0xf1, 0xc2,
	0x6f, 0xd8, 0x22, 0x7b, 0x0d, 0x1f, 0x6f, 0x79, 0x2b, 0xba, 0x2d, 0xdf, 0xc9, 0xd2, 0xa9, 0xbd,
	0x34, 0x07, 0x47, 0xbb, 0xbe, 0x28, 0x1e, 0x0f, 0x89, 0x77, 0x41, 0xf7, 0x9f, 0x8c, 0x50, 0x5c,
	0x0f, 0xdc, 0x84, 0xb8, 0xb9, 0xd7, 0x22, 0x72, 0x0d, 0x70, 0xcf, 0x0f, 0xda, 0x95, 0x7b, 0x23,
	0x64, 0x74, 0x91, 0x94, 0xb7, 0x46, 0x48, 0xbf, 0x51, 0xde, 0x22, 0xd9, 0xd2, 0x84, 0x64, 0xd7,
	0x65, 0x33, 0xea, 0x62, 0x11, 0xd4, 0x55, 0x10, 0xf3, 0xbf, 0x46, 0x90, 0x0e, 0x1f, 0x04, 0xcb,
	0x61, 0xc1, 0x51, 0x95, 0x68, 0xac, 0x2b, 0x1b, 0xff, 0xf1, 0x84, 0xce, 0xe7, 0x1c, 0xd5, 0xc6,
	0x58, 0xf7, 0x93, 0xc5, 0xfa, 0x01, 0xb3, 0x75, 0x0e, 0xfb, 0x15, 0x8a, 0xcc, 0xcf, 0xce, 0x21,
	0xfb, 0x22, 0x30, 0xc7, 0xad, 0x72, 0x92, 0x06, 0x75, 0x41, 0x46, 0x5d, 0x71, 0x54, 0xbf, 0x47,
	0x8d, 0x7d, 0x05, 0x8f, 0x3c, 0x44, 0x83, 0x97, 0xa2, 0xd4, 0xbc, 0xed, 0xf7, 0xc8, 0x9f, 0x5d,
	0x05, 0x75, 0xcd, 0xdb, 0x6a, 0x4a, 0xff, 0xbb, 0xdf, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x90,
	0x19, 0x5c, 0x83, 0x87, 0x05, 0x00, 0x00,
}
