name: Build On Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: [ ubuntu ]
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.io
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get -v -t -d ./
      - name: Clear Build
        run: rm -rf ./build && mkdir build
      - name: Build
        run: go build -o build/minerd -v -ldflags "-s -w" github.com/Sukhavati-Labs/go-miner ./
#      - name: Test
#        run: go test -v ./...
#      - name: Stop Miner Service
#        run: sudo systemctl stop skt-minerd
#      - name: Clear Old Miner Bin
#        run: rm -rf /data/miner/bin
#      - name: Update Miner Service
#        run: mv build /data/miner/bin
#      - name: Start Miner Service
#        run: sudo systemctl start skt-minerd
